### ISSUE TITLE
Import Images into project

### ISSUE THREAD

**Issue by gecko231** [dinguses/house#38]

**Comment by KevinMGranger** [comment]
What does this mean tho

Like stuff in google drive that isn't in the project yet?

If you mean the stuff that's already present in the "resources" folder, that *should* be available to the game already-- if they aren't, that means we have a bug.

**Comment by gecko231** [comment]
Yeah, stuff that's not in the project yet, since the methodology to properly show the right images didn't exist yet. Like a lot of the kitchen image stuff.
