### ISSUE TITLE
XML Parser

### ISSUE THREAD

**Issue by gecko231** [dinguses/house#8]

**Comment by KevinMGranger** [comment]
We can base it off of stuff in [here (from DogArm)](https://github.com/gecko231/DogArm/blob/master/Assets/Scripts/Conversation.cs), or there's the higher-level [Xelement](http://www.dotnetperls.com/xelement), although I'm not sure if that's available in Unity (most Linq stuff isn't last I checked)

**Comment by KevinMGranger** [comment]
I've got the urge... the urge to merge.
